export const APP_TEXT = {
  headerTitle: 'Schengen Tracker',
  tabLabels: {
    overview: 'Overview',
    trips: 'Trips',
  },
  accessibility: {
    openRules: 'Open Schengen guide',
    openSettings: 'Open app settings',
    addTrip: 'Add a new stay',
  },
  alerts: {
    successTitle: 'All Set',
    clearDataSuccess: 'Everything has been cleared from this device, including your stays and app preferences.',
    proUnlockedTitle: 'Pro Unlocked',
    proUnlockedMessage: 'You now have unlimited trip tracking.',
    restoreNoPurchaseTitle: 'No Pro Purchase Found',
    restoreNoPurchaseMessage: 'No previous Pro unlock could be restored on this device yet.',
    freeLimitTitle: 'Free Limit Reached',
    freeLimitMessage: 'The free plan supports up to {limit} trips. Unlock Pro for a one-time {price} to add more trips.',
    freeLimitUnlockAction: 'Unlock Pro ({price})',
    freeLimitRestoreAction: 'Restore Purchases',
    cancelAction: 'Cancel',
    billingUnavailableTitle: 'Billing Unavailable',
    billingUnavailableMessage: 'Purchases are currently unavailable on this build. Please use an installed iOS/Android store build and try again.',
    purchaseCancelledTitle: 'Purchase Cancelled',
    purchaseCancelledMessage: 'No payment was made. You can continue with the free plan.',
    purchaseFailedTitle: 'Purchase Failed',
    purchaseFailedMessage: 'We could not complete your purchase right now. Please try again in a moment.',
    restoreFailedTitle: 'Restore Failed',
    restoreFailedMessage: 'We could not restore purchases right now. Please try again later.',
  },
  versionPrefix: 'Schengen Tracker v',
};
