export const TRIP_FORM_TEXT = {
  initialPreview: 'Pick your dates to instantly see your Schengen balance.',
  validDatePreview: 'Enter valid dates ({format}) to preview your allowance.',
  errors: {
    title: 'Error',
    overlapTitle: 'Overlap Error',
    selectCountry: 'Please choose a destination country first.',
    fillDates: 'Please enter both a start date and an end date.',
    validDates: 'Please use valid dates in this format: {format}.',
    endBeforeStart: 'Your end date cannot be earlier than your start date.',
    overlapPreview: 'Overlap warning: this overlaps with your {country} stay by {days} days. Only a 1-day travel overlap is allowed.',
    overlapAlert: 'This trip overlaps with your stay in {country} ({start} to {end}) by {days} days. You can only overlap by 1 day for travel transitions.',
  },
  header: {
    eyebrow: 'Trip Planner',
    edit: 'Edit Trip',
    add: 'Plan a New Trip',
  },
  fields: {
    stayName: 'Trip Name or Purpose (Optional)',
    stayPlaceholder: 'For example: Summer holiday, client visit',
    destinationCountry: 'Destination Country',
    searchCountries: 'Search for a country...',
    selectDestinationCountry: 'Choose Destination Country',
    startDate: 'Start Date',
    endDate: 'End Date',
  },
  preview: {
    validTitle: 'You Are Within Limits',
    invalidTitle: 'Allowance Alert',
    selectedStay: 'This trip',
    windowStays: 'Used in window',
    bufferLeft: 'Days remaining',
    days: 'Days',
  },
  actions: {
    cancel: 'Cancel',
    save: 'Save Trip',
    update: 'Update Trip',
    useToday: 'Use Today',
    selectStartDate: 'Pick Start Date',
    selectEndDate: 'Pick End Date',
  },
  weekdays: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
};
