import { writeFile } from 'node:fs/promises';

const landmarkTitles = {
  austria: 'Schonbrunn Palace',
  belgium: 'Grand Place',
  croatia: 'Dubrovnik',
  czechia: 'Charles Bridge',
  denmark: 'Nyhavn',
  estonia: 'Tallinn Old Town',
  finland: 'Helsinki Cathedral',
  france: 'Eiffel Tower',
  germany: 'Brandenburg Gate',
  greece: 'Acropolis of Athens',
  hungary: 'Hungarian Parliament Building',
  iceland: 'Hallgrimskirkja',
  italy: 'Colosseum',
  latvia: 'Riga',
  liechtenstein: 'Vaduz Castle',
  lithuania: "Gediminas' Tower",
  luxembourg: 'Vianden Castle',
  malta: "St John's Co-Cathedral",
  netherlands: 'Kinderdijk',
  norway: 'Geirangerfjord',
  poland: 'Wawel Castle',
  portugal: 'Belem Tower',
  slovakia: 'Bratislava Castle',
  slovenia: 'Lake Bled',
  spain: 'Sagrada Familia',
  sweden: 'Gamla stan',
  switzerland: 'Matterhorn',
};

const apiBase = 'https://en.wikipedia.org/w/api.php';

function buildQuery(title) {
  const params = new URLSearchParams({
    action: 'query',
    prop: 'pageimages|info',
    piprop: 'thumbnail|original|name',
    pithumbsize: '1400',
    inprop: 'url',
    redirects: '1',
    format: 'json',
    origin: '*',
    titles: title,
  });
  return `${apiBase}?${params.toString()}`;
}

async function fetchImage(title) {
  let response;
  for (let attempt = 0; attempt < 5; attempt += 1) {
    response = await fetch(buildQuery(title));
    if (response.ok) {
      break;
    }
    if (response.status !== 429) {
      throw new Error(`Wikipedia API request failed for ${title}: ${response.status}`);
    }
    await new Promise((resolve) => setTimeout(resolve, 500 * (attempt + 1)));
  }

  if (!response || !response.ok) {
    throw new Error(`Wikipedia API request failed for ${title}: ${response?.status ?? 'unknown'}`);
  }

  const data = await response.json();
  const pages = data?.query?.pages ?? {};
  const page = Object.values(pages)[0];

  if (!page || page.missing !== undefined) {
    throw new Error(`No page found for ${title}`);
  }

  const imageUrl = page.thumbnail?.source || page.original?.source;
  if (!imageUrl) {
    throw new Error(`No image available for ${title}`);
  }

  return {
    title: page.title,
    sourcePage: page.fullurl || `https://en.wikipedia.org/wiki/${encodeURIComponent(page.title)}`,
    imageUrl,
  };
}

function toTypeScript(map) {
  const lines = [];
  lines.push('/**');
  lines.push(' * @license');
  lines.push(' * SPDX-License-Identifier: Apache-2.0');
  lines.push(' *');
  lines.push(' * Generated by scripts/generateCountryLandmarkImages.mjs');
  lines.push(' */');
  lines.push('');
  lines.push('export const COUNTRY_LANDMARK_IMAGES = {');

  for (const [countryId, value] of Object.entries(map)) {
    lines.push(`  ${countryId}: '${value.imageUrl}',`);
  }

  lines.push('} as const;');
  lines.push('');
  lines.push('export const COUNTRY_LANDMARK_SOURCES = {');

  for (const [countryId, value] of Object.entries(map)) {
    lines.push(`  ${countryId}: {`);
    lines.push(`    landmarkTitle: '${value.title.replace(/'/g, "\\'")}',`);
    lines.push(`    sourcePage: '${value.sourcePage}',`);
    lines.push('  },');
  }

  lines.push('} as const;');
  lines.push('');
  return lines.join('\n');
}

async function main() {
  const result = {};

  for (const [countryId, title] of Object.entries(landmarkTitles)) {
    process.stdout.write(`Resolving ${countryId} -> ${title}... `);
    try {
      result[countryId] = await fetchImage(title);
      process.stdout.write('ok\n');
      await new Promise((resolve) => setTimeout(resolve, 150));
    } catch (error) {
      process.stdout.write(`failed (${error.message})\n`);
      process.exitCode = 1;
      return;
    }
  }

  const outTs = toTypeScript(result);
  await writeFile('src/content/countryLandmarkImages.ts', outTs, 'utf8');
  process.stdout.write('Generated src/content/countryLandmarkImages.ts\n');
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
